name: "Image Analysis Graph"

grouped_by_type:
  url: "https://graphxr.kineviz.com/share/65ee53572ae7517560f0e78f/Image%20Analysis%20and%20Object%20Detection%20Using%20Deep%20Learning/65ee5cfd2ae7517560f0f247/object_image_analysis_graph"
  password: "BD7S83248k9qkdDKaEnb"

grouped_by_louvain_components:
  url: "https://graphxr.kineviz.com/share/65ee53572ae7517560f0e78f/Image%20Analysis%20and%20Object%20Detection%20Using%20Deep%20Learning/65ee63592ae7517560f0f86c/object_image_analysis_graph_louvain"
  password: "BD7S83248k9qkdDKaEnb"

grouped_by_strong_components:
  url: "https://graphxr.kineviz.com/share/65ee53572ae7517560f0e78f/Image%20Analysis%20and%20Object%20Detection%20Using%20Deep%20Learning/65ee643a2ae7517560f0f94c/object_image_analysis_graph_strong_component"
  password: "BD7S83248k9qkdDKaEnb"