name: "Image Analysis Graph"

v-0.0.1:
  url: "https://graphxrdev.kineviz.com/share/6611432603db55c12d50ce5b/Image%20Analysis%20and%20Object%20Detection%20using%20Deep%20Learning/6611517503db55c12d50e281/Image%20Analysis%20and%20Object%20Detection%20Using%20Deep%20Learning%20v-0.0.1"
  password: "BD7S83248k9qkdDKaEnb"